
version: "2"
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes:
      - .:/home/dev/github_deploy/django-docker-project/django-project
    ports:
      - "8000:8000"
